from pathlib import Path
import re

ROOT = Path(__file__).parent
OUT = ROOT / "bot.cpp"

# 按依赖顺序合并
FILES = [
    "Common.h",
    "ChessBoard.h",
    "AIPlayer.h",
    "Protocol.h",
    "ChessBoard.cpp",
    "AIPlayer.cpp",
    "Protocol.cpp",
    "main.cpp",
]

# 项目内部头文件，合并后删掉这些 include
LOCAL_HEADERS = {
    "Common.h",
    "ChessBoard.h",
    "AIPlayer.h",
    "Protocol.h",
}

include_local_pattern = re.compile(r'^\s*#\s*include\s*"([^"]+)"')

def strip_bom(text: str) -> str:
    if text.startswith("\ufeff"):
        return text[1:]
    return text

def process_file(path: Path) -> str:
    # 用 utf-8-sig 读，自动吃掉 BOM
    text = path.read_text(encoding="utf-8-sig")
    text = strip_bom(text)
    lines = text.splitlines()

    out_lines = []
    for line in lines:
        m = include_local_pattern.match(line)
        if m:
            inc = m.group(1)
            if inc in LOCAL_HEADERS:
                # 本地头文件 include 在单文件里删除
                continue

        # 这里不要再删 #ifndef / #define / #endif
        # 否则会把 Protocol.h 里的 #ifdef _BOTZONE_ONLINE 搞坏
        out_lines.append(line)

    # 去掉首尾多余空行，但保留文件内部结构
    body = "\n".join(out_lines).strip()
    return body + "\n"

def main():
    chunks = []
    chunks.append("// ============================================================\n")
    chunks.append("// Auto-generated Botzone single-file submission\n")
    chunks.append("// Generated by merge_bot.py\n")
    chunks.append("// Do not edit this file directly; edit the multi-file project.\n")
    chunks.append("// ============================================================\n\n")

    for rel in FILES:
        path = ROOT / rel
        if not path.exists():
            raise FileNotFoundError(f"Missing file: {rel}")

        chunks.append(f"// ===================== BEGIN {rel} =====================\n\n")
        chunks.append(process_file(path))
        chunks.append(f"\n// ====================== END {rel} =====================\n\n")

    OUT.write_text("".join(chunks), encoding="utf-8", newline="\n")
    print(f"Generated: {OUT}")

if __name__ == "__main__":
    main()