import os
import re

OUTPUT_FILE = "bot.cpp"

# 头文件先，源文件后
FILES = [
    "Common.h",
    "ChessBoard.h",
    "MoveBook.h",
    "AIPlayer.h",
    "Protocol.h",

    "ChessBoard.cpp",
    "MoveBook.cpp",
    "AIPlayer.cpp",
    "Protocol.cpp",
    "main.cpp",
]

# 自动从 FILES 中提取项目内部头文件，避免以后新增头文件忘记更新
INTERNAL_HEADERS = {
    path for path in FILES if path.endswith(".h")
}


def file_exists(path: str) -> bool:
    return os.path.isfile(path)


def read_text(path: str) -> str:
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        return f.read()


def strip_include_guards(text: str) -> str:
    lines = text.splitlines()

    # 去掉传统 include guard:
    # #ifndef XXX
    # #define XXX
    if len(lines) >= 2 and lines[0].startswith("#ifndef") and lines[1].startswith("#define"):
        lines = lines[2:]

    # 去掉末尾空行
    while lines and lines[-1].strip() == "":
        lines.pop()

    # 去掉末尾 #endif
    if lines and lines[-1].strip().startswith("#endif"):
        lines.pop()

    return "\n".join(lines) + "\n"


def strip_local_includes(text: str) -> str:
    """
    去掉项目内部头文件引用，例如:
    #include "Common.h"
    #include "ChessBoard.h"
    #include "MoveBook.h"
    #include "AIPlayer.h"
    #include "Protocol.h"

    保留系统头文件、第三方库头文件等。
    """
    new_lines = []
    for line in text.splitlines():
        m = re.match(r'^\s*#include\s+"([^"]+)"', line)
        if m:
            header = m.group(1)
            if header in INTERNAL_HEADERS:
                continue
        new_lines.append(line)

    return "\n".join(new_lines) + "\n"


def normalize_blank_lines(text: str) -> str:
    # 连续 3 个及以上空行压成 2 个
    return re.sub(r"\n{3,}", "\n\n", text)


def process_file(path: str) -> str:
    text = read_text(path)

    if path.endswith(".h"):
        text = strip_include_guards(text)

    text = strip_local_includes(text)
    text = normalize_blank_lines(text)

    banner = f"// ===================== BEGIN {path} =====================\n\n"
    footer = f"\n// ====================== END {path} =====================\n"
    return banner + text.rstrip() + "\n" + footer + "\n"


def main():
    merged_parts = []
    merged_parts.append("// ============================================================\n")
    merged_parts.append("// Auto-generated Botzone single-file submission\n")
    merged_parts.append("// Generated by merge_bot.py\n")
    merged_parts.append("// Do not edit this file directly; edit the multi-file project.\n")
    merged_parts.append("// ============================================================\n\n")

    missing_required = []
    merged_count = 0

    for path in FILES:
        if file_exists(path):
            merged_parts.append(process_file(path))
            merged_parts.append("\n")
            merged_count += 1
        else:
            if path not in OPTIONAL_SOURCES:
                missing_required.append(path)

    if missing_required:
        print("以下必需文件不存在，未生成 bot.cpp：")
        for path in missing_required:
            print(" -", path)
        return

    merged_text = "".join(merged_parts)
    merged_text = normalize_blank_lines(merged_text)

    with open(OUTPUT_FILE, "w", encoding="utf-8", newline="\n") as f:
        f.write(merged_text)

    print(f"已生成 {OUTPUT_FILE}，共合并 {merged_count} 个文件。")


if __name__ == "__main__":
    main()