import os
import re

OUTPUT_FILE = "bot.cpp"

# 头文件先放前面，源文件后放后面
# 新增的 OpeningBook / TacticalRules 已加入
FILES = [
    "Common.h",
    "ChessBoard.h",
    "TacticalRules.h",
    "OpeningBook.h",
    "AIPlayer.h",
    "Protocol.h",

    "ChessBoard.cpp",
    "TacticalRules.cpp",
    "OpeningBook.cpp",
    "AIPlayer.cpp",
    "Protocol.cpp",
    "main.cpp",
]


def file_exists(path: str) -> bool:
    return os.path.isfile(path)


def read_text(path: str) -> str:
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        return f.read()


def strip_include_guards(text: str) -> str:
    lines = text.splitlines()

    # 去掉开头的 #ifndef / #define
    if len(lines) >= 2 and lines[0].startswith("#ifndef") and lines[1].startswith("#define"):
        lines = lines[2:]

    # 去掉末尾的 #endif（通常是 include guard 的结尾）
    while lines and lines[-1].strip() == "":
        lines.pop()

    if lines and lines[-1].strip().startswith("#endif"):
        lines.pop()

    return "\n".join(lines) + "\n"


def strip_local_includes(text: str) -> str:
    """
    去掉项目内部头文件引用，例如:
    #include "Common.h"
    #include "ChessBoard.h"
    #include "AIPlayer.h"
    #include "OpeningBook.h"
    #include "TacticalRules.h"
    #include "Protocol.h"
    保留系统头文件和 json 相关 include。
    """
    internal_headers = {
        "Common.h",
        "ChessBoard.h",
        "AIPlayer.h",
        "Protocol.h",
        "OpeningBook.h",
        "TacticalRules.h",
    }

    new_lines = []
    for line in text.splitlines():
        m = re.match(r'^\s*#include\s+"([^"]+)"', line)
        if m:
            header = m.group(1)
            if header in internal_headers:
                continue
        new_lines.append(line)

    return "\n".join(new_lines) + "\n"


def normalize_blank_lines(text: str) -> str:
    # 把连续 3 个以上空行压成 2 个
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def process_file(path: str) -> str:
    text = read_text(path)

    if path.endswith(".h"):
        text = strip_include_guards(text)

    text = strip_local_includes(text)
    text = normalize_blank_lines(text)

    banner = f"// ===================== BEGIN {path} =====================\n\n"
    footer = f"\n// ====================== END {path} =====================\n"
    return banner + text.rstrip() + "\n" + footer + "\n"


def main():
    merged_parts = []
    merged_parts.append("// ============================================================\n")
    merged_parts.append("// Auto-generated Botzone single-file submission\n")
    merged_parts.append("// Generated by merge_bot.py\n")
    merged_parts.append("// Do not edit this file directly; edit the multi-file project.\n")
    merged_parts.append("// ============================================================\n\n")

    missing_required = []
    merged_count = 0

    for path in FILES:
        if file_exists(path):
            merged_parts.append(process_file(path))
            merged_parts.append("\n")
            merged_count += 1
        else:
            # 这两个 cpp 允许不存在
            if path not in {"OpeningBook.cpp", "TacticalRules.cpp"}:
                missing_required.append(path)

    if missing_required:
        print("以下必需文件不存在，未生成 bot.cpp：")
        for path in missing_required:
            print(" -", path)
        return

    merged_text = "".join(merged_parts)
    merged_text = normalize_blank_lines(merged_text)

    with open(OUTPUT_FILE, "w", encoding="utf-8", newline="\n") as f:
        f.write(merged_text)

    print(f"已生成 {OUTPUT_FILE}，共合并 {merged_count} 个文件。")


if __name__ == "__main__":
    main()